src/main/resources/wa-task-permissions-privatelaw-prlapps.dmn
src/test/java/uk/gov/hmcts/reform/prl/taskconfiguration/dmn/CamundaTaskPermissionTest.java

https://tools.hmcts.net/jira/browse/FPET-1167
```
[ ] Yes
[ ] No
```

FPET-1167 Work allocation tasks skils updated

---

src/main/resources/wa-task-configuration-privatelaw-prlapps.dmn
src/main/resources/wa-task-initiation-privatelaw-prlapps.dmn
src/main/resources/wa-task-permissions-privatelaw-prlapps.dmn
src/main/resources/wa-task-types-privatelaw-prlapps.dmn
src/test/java/uk/gov/hmcts/reform/prl/taskconfiguration/dmn/CamundaTaskConfigurationTest.java
src/test/java/uk/gov/hmcts/reform/prl/taskconfiguration/dmn/CamundaTaskInitiationTest.java
src/test/java/uk/gov/hmcts/reform/prl/taskconfiguration/dmn/CamundaTaskTypeFilterTest.java

https://tools.hmcts.net/jira/browse/PRL-6262
https://tools.hmcts.net/jira/browse/PRL-6155
https://tools.hmcts.net/jira/browse/PRL-5951
Cafcass path finder, open, close cases
```
[ ] Yes
[x] No
```

WA task configured for Reopen cases in issue state

---

src/main/resources/wa-task-completion-privatelaw-prlapps.dmn
src/test/java/uk/gov/hmcts/reform/prl/taskconfiguration/dmn/CamundaTaskCompletionTest.java

INC5668965 confidential check unlinked from tasks

---

src/main/resources/wa-task-configuration-privatelaw-prlapps.dmn
src/main/resources/wa-task-initiation-privatelaw-prlapps.dmn
src/main/resources/wa-task-permissions-privatelaw-prlapps.dmn
src/test/java/uk/gov/hmcts/reform/prl/taskconfiguration/dmn/CamundaTaskConfigurationTest.java
src/test/java/uk/gov/hmcts/reform/prl/taskconfiguration/dmn/CamundaTaskInitiationTest.java
src/test/java/uk/gov/hmcts/reform/prl/taskconfiguration/dmn/CamundaTaskPermissionTest.java

https://tools.hmcts.net/jira/browse/PRL-6564
```
[ ] Yes
[ ] No
```

PRL-6564 Hearing status change notification to court admin

---

src/main/resources/wa-task-completion-privatelaw-prlapps.dmn
src/test/java/uk/gov/hmcts/reform/prl/taskconfiguration/dmn/CamundaTaskCompletionTest.java

Reverts hmcts/prl-wa-task-configuration#187

Revert "INC5668965 confidential check unlinked from tasks"

---

src/main/resources/wa-task-completion-privatelaw-prlapps.dmn
src/test/java/uk/gov/hmcts/reform/prl/taskconfiguration/dmn/CamundaTaskCompletionTest.java

ChangeAutocomplete for FL401Sendtogatekeeper

---

src/main/resources/wa-task-completion-privatelaw-prlapps.dmn
src/test/java/uk/gov/hmcts/reform/prl/taskconfiguration/dmn/CamundaTaskCompletionTest.java

Reverts hmcts/prl-wa-task-configuration#193

Revert "ChangeAutocomplete for FL401Sendtogatekeeper"

---

src/main/resources/wa-task-completion-privatelaw-prlapps.dmn
src/test/java/uk/gov/hmcts/reform/prl/taskconfiguration/dmn/CamundaTaskCompletionTest.java

INC5672431-Change case number

---

src/main/resources/wa-task-completion-privatelaw-prlapps.dmn
src/test/java/uk/gov/hmcts/reform/prl/taskconfiguration/dmn/CamundaTaskCompletionTest.java

INC5676294-Uncouple Send to Gatekeeper

---

src/main/resources/wa-task-completion-privatelaw-prlapps.dmn
src/test/java/uk/gov/hmcts/reform/prl/taskconfiguration/dmn/CamundaTaskCompletionTest.java

INC5676294-Revert uncoupling Send to Gatekeeper

---

src/main/resources/wa-task-cancellation-privatelaw-privatelaw_exceptionrecord.dmn
src/main/resources/wa-task-cancellation-privatelaw-prlapps.dmn
src/main/resources/wa-task-completion-privatelaw-privatelaw_exceptionrecord.dmn
src/main/resources/wa-task-completion-privatelaw-prlapps.dmn
src/main/resources/wa-task-configuration-privatelaw-privatelaw_exceptionrecord.dmn
src/main/resources/wa-task-configuration-privatelaw-prlapps.dmn
src/main/resources/wa-task-initiation-privatelaw-privatelaw_exceptionrecord.dmn
src/main/resources/wa-task-initiation-privatelaw-prlapps.dmn
src/main/resources/wa-task-permissions-privatelaw-privatelaw_exceptionrecord.dmn
src/main/resources/wa-task-permissions-privatelaw-prlapps.dmn
src/main/resources/wa-task-types-privatelaw-privatelaw_exceptionrecord.dmn
src/main/resources/wa-task-types-privatelaw-prlapps.dmn

https://tools.hmcts.net/jira/browse/FPET-1238 
```
[ ] Yes
[ ] No
```

FPET-1238 added TTL for all dmns

---

src/main/resources/wa-task-cancellation-privatelaw-privatelaw_exceptionrecord.dmn

[FPET-1238](https://tools.hmcts.net/jira/browse/FPET-1238)
```
[ ] Yes
[ ] No
```

FPET-1238 workallocation changes

---

src/main/resources/wa-task-permissions-privatelaw-prlapps.dmn
src/test/java/uk/gov/hmcts/reform/prl/taskconfiguration/dmn/CamundaTaskPermissionTest.java

https://tools.hmcts.net/jira/browse/PRL-6984
Added ability for CTSC admin to mark the HWF tasks as done manually
```
[ ] Yes
[x] No
```

PRL-6984 - Added ability for CTSC admin to mark the HWF tasks as done manually

---

src/main/resources/wa-task-completion-privatelaw-prlapps.dmn
src/test/java/uk/gov/hmcts/reform/prl/taskconfiguration/dmn/CamundaTaskCompletionTest.java

FPVTL-118-Decouple Send to Gatekeeper task.

---

src/main/resources/wa-task-completion-privatelaw-prlapps.dmn
src/test/java/uk/gov/hmcts/reform/prl/taskconfiguration/dmn/CamundaTaskCompletionTest.java

FPVTL-118 Reverse decoupling of Gatekeeping task

---

src/main/resources/wa-task-completion-privatelaw-prlapps.dmn
src/test/java/uk/gov/hmcts/reform/prl/taskconfiguration/dmn/CamundaTaskCompletionTest.java

FPVTL-122: Unable to Issue application to the Court INC5695070

---

src/main/resources/wa-task-completion-privatelaw-prlapps.dmn
src/test/java/uk/gov/hmcts/reform/prl/taskconfiguration/dmn/CamundaTaskCompletionTest.java

Fpvtl 171 reverse decoupling of gatekeeping task

---

charts/prl-task-configuration/Chart.yaml

FPVTL-119
```
[ ] Yes
[x] No
```

FPVTL-119 oci helm

---

src/main/resources/wa-task-completion-privatelaw-prlapps.dmn
src/test/java/uk/gov/hmcts/reform/prl/taskconfiguration/dmn/CamundaTaskCompletionTest.java

tl-606
fpv### JIRA link (if applicable) ###
```
[ ] Yes
[ ] No
```

FPVTL-606 decouple gatekeeper for incident

---

src/main/resources/wa-task-completion-privatelaw-prlapps.dmn
src/test/java/uk/gov/hmcts/reform/prl/taskconfiguration/dmn/CamundaTaskCompletionTest.java

FPVTL-606
```
[ ] Yes
[x] No
```

FPVTL-606 decouple gatekeeper for incident fix casing

---

src/main/resources/wa-task-completion-privatelaw-prlapps.dmn
src/test/java/uk/gov/hmcts/reform/prl/taskconfiguration/dmn/CamundaTaskCompletionTest.java

FPVTL-606
```
[ ] Yes
[x] No
```

FPVTL-606 return coupling for SendToGateKeeper

---

src/main/resources/wa-task-permissions-privatelaw-prlapps.dmn
src/test/java/uk/gov/hmcts/reform/prl/taskconfiguration/dmn/CamundaTaskPermissionTest.java

FPVTL-495: DA 'send to Gatekeeper' task update

---

src/main/resources/wa-task-cancellation-privatelaw-prlapps.dmn
src/main/resources/wa-task-completion-privatelaw-prlapps.dmn
src/main/resources/wa-task-configuration-privatelaw-prlapps.dmn
src/main/resources/wa-task-initiation-privatelaw-prlapps.dmn
src/test/java/uk/gov/hmcts/reform/prl/taskconfiguration/dmn/CamundaTaskCancellationTest.java
src/test/java/uk/gov/hmcts/reform/prl/taskconfiguration/dmn/CamundaTaskCompletionTest.java
src/test/java/uk/gov/hmcts/reform/prl/taskconfiguration/dmn/CamundaTaskConfigurationTest.java
src/test/java/uk/gov/hmcts/reform/prl/taskconfiguration/dmn/CamundaTaskInitiationTest.java

https://tools.hmcts.net/jira/browse/FPVTL-497
Replace C100ManageFlags with c100CheckWaTaskStatus
```
[ ] Yes
[X] No
```

FPVTL-497 Review RA request

---

src/main/resources/wa-task-completion-privatelaw-prlapps.dmn
src/test/java/uk/gov/hmcts/reform/prl/taskconfiguration/dmn/CamundaTaskCompletionTest.java

Resolves: https://tools.hmcts.net/jira/browse/FPVTL-920 
URGENT

FPVTL-920 Decouple Gatekeeping Task

---

src/main/resources/wa-task-completion-privatelaw-prlapps.dmn
src/test/java/uk/gov/hmcts/reform/prl/taskconfiguration/dmn/CamundaTaskCompletionTest.java

Patching: https://tools.hmcts.net/jira/browse/FPVTL-936

FPVTL-936 Reverse Decoupling of Gatekeeping Task

---

src/main/resources/wa-task-completion-privatelaw-prlapps.dmn
src/test/java/uk/gov/hmcts/reform/prl/taskconfiguration/dmn/CamundaTaskCompletionTest.java

FPVTL-951
- Decouple gatekeeping task
```
[ ] Yes
[X] No
```

FPVTL-951: Decouple gatekeeping task

---

src/main/resources/wa-task-completion-privatelaw-prlapps.dmn
src/test/java/uk/gov/hmcts/reform/prl/taskconfiguration/dmn/CamundaTaskCompletionTest.java

FPVTL-988 Decouple gatekeeping task

---

build.gradle
config/owasp/suppressions.xml
src/main/resources/wa-task-completion-privatelaw-prlapps.dmn
src/main/resources/wa-task-initiation-privatelaw-prlapps.dmn
src/main/resources/wa-task-permissions-privatelaw-prlapps.dmn
src/test/java/uk/gov/hmcts/reform/prl/taskconfiguration/dmn/CamundaTaskInitiationTest.java
src/test/java/uk/gov/hmcts/reform/prl/taskconfiguration/dmn/CamundaTaskPermissionTest.java

FPVTL-984
```
[ ] Yes
[x] No
```

FPVTL-984 listOnNoticeHearingC100 initiation and fix identifier on listOnNoticeHearingFL401

---

src/main/resources/wa-task-completion-privatelaw-prlapps.dmn
src/test/java/uk/gov/hmcts/reform/prl/taskconfiguration/dmn/CamundaTaskCompletionTest.java

FPVTL-1112 Decouple gatekeeping tasks

---

src/main/resources/wa-task-completion-privatelaw-prlapps.dmn
src/test/java/uk/gov/hmcts/reform/prl/taskconfiguration/dmn/CamundaTaskCompletionTest.java

FPVTL-1112 Reverse decoupling of gatekeeping for CA & DA cases

---

src/main/resources/wa-task-completion-privatelaw-prlapps.dmn
src/test/java/uk/gov/hmcts/reform/prl/taskconfiguration/dmn/CamundaTaskCompletionTest.java

FPVTL-1251 Decoupling of gatekeeping for CA case

---

src/main/resources/wa-task-completion-privatelaw-prlapps.dmn
src/test/java/uk/gov/hmcts/reform/prl/taskconfiguration/dmn/CamundaTaskCompletionTest.java

https://tools.hmcts.net/jira/browse/FPVTL-1156
Add new Line with Events
```
[ ] Yes
[X] No
```

FPVTL-1156 : Add new Line with Events
